chart-dirs:
    - scripts/helm
chart-repos:
    - bitnami=https://charts.bitnami.com/bitnami
    - elastic=https://helm.elastic.co
    - hashicorp=https://helm.releases.hashicorp.com
    - rajan=https://raw.githubusercontent.com/rajan123456/helm-charts/master
    - stable=https://kubernetes-charts.storage.googleapis.com
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
