chart-dirs:
    - scripts/helm
  chart-repos:
    - rajan=https://raw.githubusercontent.com/rajan123456/helm-charts/master
  check-version-increment: true
  debug: true
  remote: origin
  validate-chart-schema: true
  validate-maintainers: true
  validate-yaml: true