apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: production
spec:
  selector:
    app: spark
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: spark-ui
    - protocol: TCP
      port: 7077
      targetPort: 7077
      name: spark-master
