apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.global.namespaceOverride}}
spec:
  replicas: {{.Values.deployment.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{.Chart.Name}}
  strategy:
    type: {{.Values.deployment.strategy}}
    {{- if eq .Values.deployment.strategy "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{.Values.deployment.rollingUpdate.maxSurge}}
      maxUnavailable: {{.Values.deployment.rollingUpdate.maxUnavailable}}
    {{- end }}
  progressDeadlineSeconds: {{.Values.deployment.progressDeadlineSeconds}}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{.Chart.Name}}
    spec:
      containers:
        - image: {{.Values.deployment.image.repository}}:{{.Values.deployment.image.tag}}
          name: {{.Chart.Name}}
          {{- if .Values.deployment.resources }}
          resources: {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{.Values.deployment.imagePullPolicy}}
          {{- if .Values.deployment.containerPort.enabled }}
          ports:
            {{- range .Values.deployment.containerPort.portNumbers }}
            - containerPort: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.env }}
          env:
            {{- range $key, $val := .Values.deployment.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.volumeMounts.enabled }}
          volumeMounts:
          {{- range $val := .Values.deployment.volumeMounts.mountDetails }}
            - mountPath: {{$val.mountPath}}
              name: {{$val.name}}
          {{- end }}
          {{- end }}
      {{- if .Values.deployment.volumeMounts.enabled }}
      volumes:
      {{- range $val := .Values.deployment.volumeMounts.mountDetails }}
        - name: {{$val.name}}
          persistentVolumeClaim:
            claimName: {{$val.claimName}}
            readOnly: {{$val.readOnly}}
      {{- end }}
      {{- end }}
