apiVersion: v2
name: microservice
home: https://github.com/rajan123456/uPresent
appVersion: "1.0.0"
description: Generic Helm chart for uPresent microservice deployment
version: 1.0.0
type: application
maintainers:
  - name: rajan123456
sources:
  - https://github.com/rajan123456/uPresent
