##Defaults to uPresent Attendance Service

global:
  namespaceOverride: default

deployment:
  replicaCount: 2
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 50%
  progressDeadlineSeconds: 10
  image:
    repository: rajagupt/attendance
    tag: 1.0.0
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
  containerPort: 5000
  env:
    SAGA_ENABLED: 1
    REPORT_PUBLISH_API: http://reporting:8080/reporting
    FACENET_RECOGNITION_API: http://facenet:5000/api/face/
    MODULE_API_FETCH_DETAILS: http://management:8080/manage/module?moduleCode=
    MANAGEMENT_API_GEO_FENCE: http://management:8080/manage/school/geo-fence?schoolCode=
    MANAGEMENT_API_SCHOOL: http://management:8080/manage/school?schoolCode=
    USER_API_FETCH_USER: http://user:8080/user?username=
    AZURE_FACE_ENABLED: 0
    AWS_REKOG_ENABLED: 0
    FACENET_ENABLED: 1
  volumeMounts:
    enabled: true
    mountPath: /app/resources/images
    name: user-data-vol
    readOnly: true
    claimName: user-data-vol-claim

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  name: user-data-vol
  claimName: user-data-vol-claim
  storage: 10Gi

autoscaler:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

service:
  type: ClusterIP
  protocol: TCP
  port: 5000
  targetPort: 5000

ingress:
  annotations:
    ingressClass: nginx
    tlsAcme: true
    clusterIssuer: letsencrypt-prod
    acmeChallengeType: http01
  servicePort: 5000
  hostName: attendance.upresent.ga
  tls:
    secretName: nginx-tls
